### ISSUE TITLE
uart_get_tx_buffer_free_size  ISSUE

### ISSUE THREAD

**Issue by PaulAnurag** [sukesh-ak/Arduino-Library-with-IDF#1]
Hi

Thank You for providing the steps on how to integrate Arduino Library with IDF.
I have followed the steps but I am always getting this error message.

../components/arduino/cores/esp32/esp32-hal-uart.c:329:19: error: implicit declaration of function 'uart_get_tx_buffer_free_size'; did you mean 'uart_get_buffered_data_len'? [-Werror=implicit-function-declaration].

What can be the possible error?
Is this because of any liking issue.

Regards
Anurag

**Comment by sukesh-ak** [comment]
> Hi
> 
> Thank You for providing the steps on how to integrate Arduino Library with IDF. I have followed the steps but I am always getting this error message.
> 
> ../components/arduino/cores/esp32/esp32-hal-uart.c:329:19: error: implicit declaration of function 'uart_get_tx_buffer_free_size'; did you mean 'uart_get_buffered_data_len'? [-Werror=implicit-function-declaration].
> 
> What can be the possible error? Is this because of any liking issue.
> 
> Regards Anurag

Not too sure. But here is a hint.

Version of `ESP32 Arduino Core` should be same as `ESP-IDF 5.x` (released version).
Current Arduino master branch version is not for `ESP-IDF 5.x` I believe.

**Comment by PaulAnurag** [comment]
Can I use https://github.com/espressif/arduino-esp32/tree/idf-release/v4.4 ? Instead?
Because I am using esp-idf version 4.4 .

**Comment by PaulAnurag** [comment]
I

> Can I use https://github.com/espressif/arduino-esp32/tree/idf-release/v4.4 ? Instead? Because I am using esp-idf version 4.4 .

I have tried the above comment but it does not work.
Can You help me how to achieve the same if I am using esp-idf version 4.4?

Regards
Anurag

**Comment by sukesh-ak** [comment]
> I
> 
> > Can I use https://github.com/espressif/arduino-esp32/tree/idf-release/v4.4 ? Instead? Because I am using esp-idf version 4.4 .
> 
> I have tried the above comment but it does not work. Can You help me how to achieve the same if I am using esp-idf version 4.4?
> 
> Regards Anurag

I am not too sure. If you are using 4.4 it should work. I am on `IDF 5.1` so cannot test it.
Maybe you are missing a header include?

Here is the error lines
https://github.com/search?q=repo%3Aespressif%2Farduino-esp32%20uart_get_tx_buffer_free_size&type=code

**Comment by PaulAnurag** [comment]
Okay I will try to figure it out why its happening.
