### ISSUE TITLE
Error with ESP-IDF V5.1

### ISSUE THREAD

**Issue by mdede439** [sukesh-ak/Arduino-Library-with-IDF#2]
Hi, thanks for your little tutorial on this, however you said we should use the most current version of ESP-IDF and Arduino but when I do that with ver 5.1 I get this error:

    Arduino-esp32 can be used with ESP-IDF versions between 4.4.0 and 4.4.99,
    but a newer version is detected: 5.1.0.

It looks like ESP-IDF does not support Arduino as a component beyond ESP-IDF 4.4.99. Do you know of an easy way to use an Arduino library within ESP-IDF other than as the arduino-as-a-component method?

**Comment by sukesh-ak** [comment]
Yes the primary SDK for ESP32 is ESP-IDF so development and update happens there.
Arduino-esp32 version gets updated slower specially since IDF 5.x had some breaking changes.
