### ISSUE TITLE
esp32-arduino requires CONFIG_FREERTOS_HZ=1000 (currently 100)

### ISSUE THREAD

**Issue by imfatant** [sukesh-ak/Arduino-Library-with-IDF#3]
I was on ESP-IDF v5.2.2, so that was the first problem. Current Arduino-esp32 requires ESP-IDF between v5.1.0 and v5.1.99. I therefore installed v5.1.4.

Now I have another problem. When I do `idf.py set-target esp32`, I get a cmake error: 
```CMake Error at components/arduino/CMakeLists.txt:298 (message):
  esp32-arduino requires CONFIG_FREERTOS_HZ=1000 (currently 100)
```
How do I set this?

**Comment by sukesh-ak** [comment]
Check in `menuconfig`.
By default target is set to `esp32` so you don't need to change that.
In case you ran build command and you want to change the setting, you should `delete the build folder first` and then use `set-target` if MCU is `ESP32-xxx`

```bash
# menuconfig -> component config -> FreeRTOS -> Tick rate (hz)
idf.py menuconfig
```

**Comment by sukesh-ak** [comment]
@imfatant 
I haven't got time to work and test this but I'm working on a wrapper to do the same without using `esp32-arduino-core`.

Base project is here. Need some work and then testing.
https://github.com/sukesh-ak/IDF-Arduino-Wrapper

**Comment by imfatant** [comment]
@sukesh-ak
Thank you. I think I got it to work eventually. I thought I was in a catch 22 because I was finding I couldn't run menuconfig until I changed CONFIG_FREERTOS_HZ, but found I needed to change CONFIG_FREERTOS_HZ in order to run menuconfig. But I got it to work somehow...
